version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_school
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: school
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
